import { CakeIcon, CameraIcon, ChevronUpIcon, ClipboardCheckIcon, CubeIcon, DocumentAddIcon, EmojiHappyIcon, LocationMarkerIcon } from '@heroicons/react/outline'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Hero from '../components/Hero'
import Layout from '../components/Layout'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Blossoms Childcare | Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Layout title="Home">
        {/* Hero */}
        <Hero />
        {/* Section 1 - 3D tour */}
        {/* Fab */}
        <Link href='#'>
          <button className='bg-yellow-300 p-3 fixed right-2 bottom-2 lg:right-52 lg:bottom-20 rounded-full shadow-lg'>
            <ChevronUpIcon className="h-8 w-8"/>
          </button>
        </Link>
        <section className='py-10 px-2 lg:px-96'>
          <h1 className='text-center text-4xl font-semibold text-pink-300 pb-10 lg:text-6xl'>3D Virtual Tour</h1>
          <div className='flex space-y-2 bg-blue-50 rounded-2xl flex-col items-center justify-center p-5'>
            <CubeIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
            <p className='text-xl text-slate-500'>Click to See Inside Our Nursery</p>
            <div className="w-12 p-1 bg-blue-300 rounded-full my-4"></div>
            <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white'>START TOUR</button>
          </div> 
        </section>
        {/* Directions Section */}
        <section className='direction-section py-10 px-2 lg:px-96'>
          <div className='grid gap-4 grid-cols-1 lg:grid-cols-3 lg:gap-7'>
            <div className='flex rounded-2xl flex-col p-2 bg-white justify-center items-center'>
              <LocationMarkerIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
              
              <p className='text-xl text-center text-slate-500'>Find text-center us easily and plan your route here.</p>
              <div className="w-12 text-center p-1 bg-blue-300 rounded-full my-4"></div>
              <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white'>GET DIRECTIONS</button>
            </div>

            <div className='flex rounded-2xl flex-col p-2 bg-white justify-center items-center'>
              <ClipboardCheckIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
              
              <p className='text-xl text-center text-slate-500'>Request a guided tour of our Nursery here</p>
              <div className="w-12 p-1 text-center bg-blue-300 rounded-full my-4"></div>
              <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white uppercase'>Book Show Around</button>
            </div>

            <div className='flex rounded-2xl flex-col p-2 bg-white justify-center items-center'>
              <DocumentAddIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
              
              <p className='text-xl text-center text-slate-500'>Request a child’s space at our children’s nursery</p>
              <div className="w-12 p-1 text-center bg-blue-300 rounded-full my-4"></div>
              <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white uppercase'>Apply For A Space</button>
            </div>

            <div className='flex rounded-2xl flex-col p-2 bg-white justify-center items-center'>
              <EmojiHappyIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
              
              <p className='text-xl text-center text-slate-500'>7am - 7pm, 7 days-a-week<br/>  8 weeks to 4 years-old<br/>Full Nursery & Pre-School<br/> Highly Qualified Practitioners</p>
              <div className="w-12 p-1 text-center bg-blue-300 rounded-full my-4"></div>
              <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white uppercase'>Our Nursery</button>
            </div>
            <div className='flex rounded-2xl flex-col p-2 bg-white justify-center items-center'>
              <CakeIcon className='h-20 w-20 bg-blue-300 text-white rounded-full p-5'/>
              
              <p className='text-xl text-center text-slate-500'> Fresh Home-cooked Meals <br/> Healthy Breakfast & Snacks <br/> Free Nappies <br/> Hot Drinks for Parents </p>
              <div className="w-12 p-1 text-center bg-blue-300 rounded-full my-4"></div>
              <button className='p-4 text-lg rounded-full border-4 font-bold border-blue-300 text-blue-300 bg-white uppercase'>OUR FEES</button>
            </div>
          </div>
        </section>
        <section className='py-10 px-2 bg-pink-300 lg:px-96 lg:flex lg:justify-between'>
          <div className='lg:flex lg:justify-center lg:items-center'>
            <h1 className='text-center text-4xl font-bold text-white py-5 lg:text-5xl'>We are just a click away</h1>
          </div>
          <div className='flex '>
            <form>
              <p className='text-white uppercase text-2xl'>Post Code</p>
              <input className='w-full p-4 bg-gray-50 border border-pin rounded-2xl' type='text' placeholder='87-0000'></input>
              <p className='text-white uppercase text-2xl'>Destination</p>
              <input disabled className='w-full p-4 bg-gray-50 border border-pin rounded-2xl' type='text' placeholder='87-9878'></input>
              <button className='p-4 text-lg rounded-full my-4 font-bold w-full  bg-blue-300 text-white uppercase'>GET DIRECTIONS</button>
            </form>
          </div>
        </section>
        <section className='bg-blue-300 py-10 w-screen lg:px-96'>
            <div className='h-full  w-full  px-5'>
              <h1 className='uppercase font-bold text-white text-4xl text-center lg:text-6xl'>Welcome to Blossoms Childcare</h1>
              <div className='text-center text-xl text-gray-100 py-5'>
                <p>Here at Blossoms Childcare, we provide a secure and loving home-from-home experience, where children can play, learn and blossom.We see everything from a parents point of view, from the standard of care we proudly provide, to making sure we have got your choice of tea, coffee or hot-chocolate ready for you when you drop off your most precious possession. It is important that you understand every step of your childs journey along the Early Years Foundation Stage; we share online learning journeys to record each childs daily progress, learning and achievements. </p>
                
                <div className='grid grid-cols-1 gap-4 py-4 h-full lg:grid-cols-3'>
                  <div className='border-2 flex flex-col justify-center items-center rounded-2xl p-2 bg-white border-white text-blue-300'>
                    <p>Parents and carers are given unique logins to access these records, and add to their story, to build strong partnerships between the nursery and home learning</p>
                    <button className='p-4 text-lg rounded-full my-4 w-1/2 font-bold  bg-blue-300 text-white uppercase'>FOR PARENTS</button>
                  </div>
                  <div className='border-2 flex flex-col justify-center items-center rounded-2xl p-2 bg-white border-white text-blue-300'>
                    <p>We carefully plan environments for 0-4 year-old children, with designated spaces for different age groups, in order for all children to achieve the best outcomes possible, through rich and varied learning experiences</p>
                    <button className='p-4 text-lg rounded-full my-4 w-1/2 font-bold  bg-blue-300 text-white uppercase'>OUR NURSERY</button>
                  </div>

                  <div className='border-2 flex flex-col justify-center items-center rounded-2xl p-2 bg-white border-white text-blue-300'>
                    <p>We accept 15 hours-a-week (2, 3 and 4 year-old) funded places, and 30 hours-a-week (3 and 4 year-old) funded places for working parents. We also accept Tax-Free Childcare and Childcare Vouchers</p>
                    <button className='p-4 text-lg rounded-full my-4 w-1/2 font-bold  bg-blue-300 text-white uppercase'>OUR FEES</button>
                  </div>
                </div>
                
              </div>
            </div>
        </section>
        {/* Welcome Section */}
        {/* 3D virtual tour */}
        {/* What makes us different */}
      </Layout>
      
    </div>
  )
}
